CC = gcc
CFLAGS = -Wall -ansi -std=c11

q1: q1.c
	$(CC) $(CFLAGS) -o q1 q1.c

q2: q2.c
	$(CC) $(CFLAGS) -o q2 q2.c

q3: q3.c
	$(CC) $(CFLAGS) -o q3 q3.c

q7: q7.c
	$(CC) $(CFLAGS) -o q7 q7.c

shell: shell.c
	$(CC) $(CFLAGS) -o shell shell.c
